language: php
php:
  - '5.6'
  - '7.0'
  - nightly
before_script:
  - composer install -n --no-interaction
script:
  - phpunit --bootstrap vendor/autoload.php tests/GeneralTest.php
  - phpunit --bootstrap vendor/autoload.php tests/WriteTest.php
  - phpunit --bootstrap vendor/autoload.php tests/UsersTest.php
